name: 'cron'

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go version

    - name: Install dependencies
      run: go get .

    - name: Check source code formatting
      run: test -z $(go fmt ./...)

    - name: Run source code analysis
      run: go list ./... | xargs go vet

    - name: Run tests
      run: go test -v -timeout 120s -race ./...

    - name: Build binary
      run: go build -v ./...
